import { ChatInputCommandInteraction, EmbedBuilder, SlashCommandBuilder } from 'discord.js'
import { questions } from '../../data/questions.js'
import { IMAGE_URLS } from '../../data/assets.js'

export const command = {
	data: new SlashCommandBuilder()
		.setName('question')
		.setDescription('Generate a random conversation starter question')
	,
	async execute(interaction: ChatInputCommandInteraction) {
		const randomIndex = Math.floor(Math.random() * questions.length)
		const question = questions[randomIndex]
		
		const questionEmbed = new EmbedBuilder()
			.setTitle('Your Random Question')
			.setDescription(question)
			.setColor('Blue')
			.setFooter({
				iconURL: IMAGE_URLS['ConversationStartersWorld_Icon.png'],
				text: 'Generated by conversationstartersworld.com'
			})
		
		interaction.reply({ embeds: [questionEmbed] })
	}
}